name: "openaq_transform"
version: "1.0.0"
config-version: 2

# This setting configures which profile dbt uses for this project.
profile: "openaq_transform"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  openaq_transform:
    # First layer: cleansing
    staging:
      +materialized: view
      +schema: openaq_staging
      +tags: ["silver", "daily", "staging"]

    # Second layer: joins
    intermediate:
      +materialized: view # ephemeral would be acceptable, but view for debugging
      +schema: openaq_intermediate
      +tags: ["silver", "daily", "intermediate"]

    # Third: consumption layer
    marts:
      +materialized: table
      +schema: openaq_marts
      +tags: ["gold", "daily", "marts"]
