openaq_transform:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_GCP_PROJECT') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET') }}"
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      # Fallback to 'europe-southwest1' if the environment variable is not set
      location: "{{ env_var('DBT_GCP_LOCATION') }}"
      priority: interactive
